<?php
namespace App\Services\Articles;
use App\Models\Article;
use Illuminate\Support\Facades\Http;
class ArticleGenerationService {
 public const NO_CANDIDATE='NO_CANDIDATE'; private int $batchSourceOk=0,$batchSourceFail=0,$batchAi=0,$batchFallback=0,$batchQualityPass=0,$batchQualityFail=0;
 public function publishNext():?Article{$r=$this->processNext();return $r['status']==='published'?$r['article']:null;}
 public function publishBatch():array{$published=$scanned=$rejected=$deferred=$failed=0;$max=(int)config('berita.news_candidate_scan_max',10);$target=(int)config('berita.news_publish_target',2);while($published<$target&&$scanned<$max){$r=$this->processNext();if($r['status']===self::NO_CANDIDATE)break;$scanned++;switch($r['status']){case'published':$published++;break;case'rejected':$rejected++;break;case'deferred':$deferred++;break;default:$failed++;}}return compact('scanned','published','rejected','deferred','failed')+['source_fetch_success'=>$this->batchSourceOk,'source_fetch_failed'=>$this->batchSourceFail,'generated_ai'=>$this->batchAi,'generated_fallback'=>$this->batchFallback,'generation_failed'=>$failed,'quality_pass'=>$this->batchQualityPass,'quality_failed'=>$this->batchQualityFail];}
 public function processNext():array{
  $a=Article::whereIn('generation_status',['pending','deferred'])->where('generation_attempts','<',(int)config('berita.news_max_generation_attempts',3))->orderByDesc('source_published_at')->first();
  if(!$a)return ['status'=>self::NO_CANDIDATE,'article'=>null];
  $a->generation_status='processing';$a->save();
  try{$extract=app(SourceArticleExtractor::class)->extract((string)$a->source_url,(string)$a->excerpt);$a->source_content=$extract['text']?:$a->source_content;$a->source_content_method=$extract['method'];$a->source_content_chars=$extract['char_count'];$a->source_fetch_status=$extract['status'];$a->source_fetched_at=now();$a->save();if($extract['status']==='ok')$this->batchSourceOk++;else $this->batchSourceFail++;
   if(in_array($extract['method'],['timeout_or_error','fetch_failed'],true)){ $a->generation_status='deferred'; $a->deferred_reason=$extract['method']; $a->save(); return ['status'=>'deferred','article'=>$a]; } if($extract['method']==='invalid_url'){ $a->generation_status='rejected'; $a->rejected_reason='invalid_source_url'; $a->save(); return ['status'=>'rejected','article'=>$a]; } if(!$extract['text']||$extract['char_count']<(int)config('berita.news_min_source_chars',1000)){$a->generation_status='deferred';$a->deferred_reason='source_too_thin';$a->save();return ['status'=>'deferred','article'=>$a];}
   if(!$a->image_url)$a->image_url=$this->discoverImage($a->source_url);if(!$a->image_url){$a->generation_status='deferred';$a->deferred_reason='image_unavailable';$a->save();return ['status'=>'deferred','article'=>$a];}
   $a->generation_attempts++;$g=$this->generate($a);if(!$g['pass']){$a->generation_status=$g['transient']?'deferred':'rejected';$a->{$g['transient']?'deferred_reason':'rejected_reason'}=$g['reason'];$a->last_generation_error=$g['reason'];$a->save();return ['status'=>$a->generation_status,'article'=>$a];}
   if(($g['mode']??'ai')==='ai')$this->batchAi++;else $this->batchFallback++;$a->title=$g['data']['title'];$a->excerpt=$g['data']['excerpt'];$a->content=$g['data']['content'];$gate=app(ArticleQualityGate::class)->check($a,$g['safety']);if(!$gate['pass']){$this->batchQualityFail++;$a->generation_status='rejected';$a->rejected_reason='quality:'.implode(',',$gate['reasons']);$a->last_generation_error=$a->rejected_reason;$a->save();return ['status'=>'rejected','article'=>$a];}
   $this->batchQualityPass++;$a->generation_status='published';$a->site_published_at=now();$a->updated_at_content=now();$a->last_generation_error=null;$a->save();return ['status'=>'published','article'=>$a];
  }catch(\Throwable $e){$a->generation_status='failed';$a->last_generation_error=substr($e->getMessage(),0,1000);$a->save();return ['status'=>'failed','article'=>$a];}
 }
 private function generate(Article $a):array{$source=$a->source_content?:$a->excerpt;$fallback=['title'=>$a->title,'excerpt'=>mb_substr(trim(strip_tags($source)),0,200),'content'=>$this->fallbackContent($source)];$key=config('berita.gemini_api_key');if(!$key)return ['pass'=>$this->safe($fallback,$a)['pass'],'data'=>$fallback,'safety'=>$this->safe($fallback,$a),'transient'=>false,'reason'=>'gemini_unconfigured'];$prompt='Anda adalah editor berita Indonesia untuk Berita Auto.\nTulis ulang berita berikut secara faktual.\nATURAN:\n- hanya gunakan fakta dari source\n- jangan membuat nama baru, angka baru, tanggal baru, lokasi baru, kutipan palsu, kejadian baru atau opini\n- jangan copy paragraf mentah source\n- parafrase natural\n- Bahasa Indonesia jurnalistik\n- jangan markdown\nReturn JSON: {"title":"...","excerpt":"...","content":"..."}\nInput: original title='.$a->title.'; publisher='.$a->publisher.'; category='.(string)optional($a->category)->name.'; source_url='.$a->source_url.'; rss_summary='.$a->excerpt.'; source_content='.$source;
  try{$url='https://generativelanguage.googleapis.com/v1beta/models/'.config('berita.gemini_model','gemini-2.5-flash-lite').':generateContent?key='.urlencode($key);$r=Http::connectTimeout(5)->timeout(20)->post($url,['contents'=>[['parts'=>[['text'=>$prompt]]]],'generationConfig'=>['responseMimeType'=>'application/json']]);if($r->status()===429||$r->serverError())return $this->fallbackResult($fallback,$a,'gemini_transient');$raw=$r->json('candidates.0.content.parts.0.text');$data=is_string($raw)?json_decode($raw,true):null;if(!is_array($data)||empty($data['title'])||empty($data['content']))return $this->fallbackResult($fallback,$a,'invalid_json');$data=['title'=>trim($data['title']),'excerpt'=>trim($data['excerpt']??''),'content'=>trim($data['content'])];$s=$this->safe($data,$a);if(!$s['pass'])return $this->fallbackResult($fallback,$a,implode(',',$s['reasons']));return ['pass'=>true,'transient'=>false,'reason'=>'','data'=>$data,'safety'=>$s,'mode'=>'ai'];}catch(\Throwable){return ['pass'=>false,'transient'=>true,'reason'=>'gemini_timeout','data'=>$fallback,'safety'=>[]];}}
 private function safe(array $d,Article $a):array{$src=$a->source_content.' '.$a->excerpt.' '.$a->title.' '.$a->publisher;$reasons=[];$nums=$this->tokens($d['title'].' '.$d['excerpt'].' '.$d['content']);foreach($nums as $n)if(!str_contains($src,$n))$reasons[]='unsupported_number:'.$n;$paras=preg_split('/\n+/',trim($d['content']));foreach($paras as $p){$p=trim($p);if(mb_strlen($p)>120&&$this->overlap($p,$a->source_content)>0.75)$reasons[]='excessive_overlap';}foreach($this->entities($d['content']) as $e)if(mb_strlen($e)>3&&!str_contains(mb_strtolower($src),mb_strtolower($e)))$reasons[]='unsupported_entity:'.$e;return ['pass'=>$reasons===[],'reasons'=>array_values(array_unique($reasons))];}
 private function tokens(string $s):array{preg_match_all('/(?:Rp\.?\s?[\d.,]+|\d+(?:[.,]\d+)?%?|\d{4}-\d{1,2}-\d{1,2})/u',$s,$m);return array_values(array_unique($m[0]));}
 private function entities(string $s):array{preg_match_all('/\b(?:[A-Z][\p{L}]+(?:\s+[A-Z][\p{L}]+){1,3})\b/u',$s,$m);return array_values(array_unique($m[0]));}
 private function overlap(string $a,string $b):float{$na=preg_split('/\W+/u',mb_strtolower($a),-1,PREG_SPLIT_NO_EMPTY);$nb=array_flip(preg_split('/\W+/u',mb_strtolower($b),-1,PREG_SPLIT_NO_EMPTY));if(!$na)return 0;$hit=0;foreach($na as $w)if(isset($nb[$w]))$hit++;return $hit/count($na);}
 private function fallbackContent(string $s):string{$p=preg_split('/(?<=[.!?])\s+/u',trim(strip_tags($s)),-1,PREG_SPLIT_NO_EMPTY);$p=array_values(array_unique(array_filter($p)));return implode("\n\n",array_slice($p,0,10));}
 private function discoverImage(?string $url):?string{if(!$url)return null;try{$r=Http::connectTimeout(3)->timeout(5)->withHeaders(['Accept'=>'text/html','User-Agent'=>'BeritaAutoBot/1.0'])->get($url);if(!$r->successful())return null;preg_match('/<meta[^>]+property=["\']og:image["\'][^>]+content=["\']([^"\']+)/i',$r->body(),$m);return isset($m[1])&&filter_var($m[1],FILTER_VALIDATE_URL)?$m[1]:null;}catch(\Throwable){return null;}}
}