<?php
namespace App\Services\Articles;
use App\Models\Article;
use Illuminate\Support\Facades\Http;
class ArticleGenerationService {
 public const NO_CANDIDATE='NO_CANDIDATE';
 public function publishNext(): ?Article { $r=$this->processNext(); return $r['status']==='published'?$r['article']:null; }
 public function publishBatch():array{$published=$scanned=$rejected=$deferred=$failed=0;$max=(int)config('berita.news_candidate_scan_max',10);$target=(int)config('berita.news_publish_target',2);while($published<$target&&$scanned<$max){$r=$this->processNext();if($r['status']==self::NO_CANDIDATE)break;$scanned++;if($r['status']==='published')$published++;elseif($r['status']==='rejected')$rejected++;elseif($r['status']==='deferred')$deferred++;else$failed++;}return compact('scanned','published','rejected','deferred','failed');}
 public function processNext():array{$a=Article::where('generation_status','pending')->where('source_published_at','>=',now()->subHours((int)config('berita.freshness_hours',12)))->orderByDesc('source_published_at')->first();if(!$a)return ['status'=>self::NO_CANDIDATE,'article'=>null];if(!$a->image_url)$a->image_url=$this->discoverImage($a->source_url);if(!$a->image_url){$a->generation_status='rejected';$a->save();return ['status'=>'rejected','article'=>$a];}$g=$this->generate($a);$a->title=$g['title'];$a->content=$g['content'];$a->excerpt=$g['excerpt'];$a->generation_status='published';$a->site_published_at=now();$a->updated_at_content=now();$a->save();return ['status'=>'published','article'=>$a];}
 private function generate(Article $a):array{$fallback=['title'=>$a->title,'content'=>$a->source_content?:$a->content,'excerpt'=>$a->excerpt];$key=config('berita.gemini_api_key');if(!$key)return $fallback;try{$model=config('berita.gemini_model','gemini-2.5-flash-lite');$url='https://generativelanguage.googleapis.com/v1beta/models/'.$model.':generateContent?key='.urlencode($key);$input=$a->source_content?:$a->content;$prompt='Tulis ulang berita berikut dalam Bahasa Indonesia secara faktual. Kembalikan JSON dengan title, excerpt, content. Judul: '.$a->title.' Sumber: '.$input;$r=Http::timeout(18)->post($url,['contents'=>[['parts'=>[['text'=>$prompt]]]],'generationConfig'=>['responseMimeType'=>'application/json']]);if(!$r->successful())return $fallback;$j=json_decode((string)$r->json('candidates.0.content.parts.0.text'),true);return is_array($j)&&!empty($j['content'])?array_merge($fallback,$j):$fallback;}catch(\Throwable){return $fallback;}}
 private function discoverImage(?string $url):?string{if(!$url)return null;try{$r=Http::timeout(5)->get($url);if(!$r->successful())return null;preg_match('/<meta[^>]+property=["\']og:image["\'][^>]+content=["\']([^"\']+)/i',$r->body(),$m);return isset($m[1])&&filter_var($m[1],FILTER_VALIDATE_URL)?$m[1]:null;}catch(\Throwable){return null;}}
}