<?php
use Illuminate\Support\Facades\Schedule;use Illuminate\Support\Facades\Artisan;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Http;use App\Models\Article;use App\Services\Automation\NewsCycleService;use App\Console\Commands\AdminConsoleProcess;
Artisan::command('berita:cycle',function(NewsCycleService $service){$this->info(json_encode($service->run()));})->purpose('Run canonical automated news cycle');
Artisan::command('berita:publish-scheduled',function(){$c=Article::where('generation_status','scheduled')->whereNotNull('scheduled_at')->where('scheduled_at','<=',now())->update(['generation_status'=>'published','site_published_at'=>now(),'updated_at_content'=>now(),'reviewed_at'=>now()]);$this->info('Published scheduled articles: '.$c);})->purpose('Publish reviewed articles whose schedule has arrived');
Artisan::command('berita:debug-rejected {--limit=20}',function(){$n=max(1,min(100,(int)$this->option('limit')));$this->line(Article::where('generation_status','rejected')->latest('updated_at')->limit($n)->get(['id','title','generation_attempts','rejected_reason','last_generation_error','source_content_method','source_content_chars','updated_at'])->toJson(JSON_PRETTY_PRINT));});
Artisan::command('berita:reset-safety-rejected',function(){$n=Article::where('generation_status','rejected')->where(function($q){$q->where('rejected_reason','excessive_overlap')->orWhere('rejected_reason','like','unsupported_entity:%');})->update(['generation_status'=>'pending','generation_attempts'=>0,'rejected_reason'=>null,'last_generation_error'=>null,'quality_score'=>null,'quality_reasons'=>null]);$this->info('RESET='.$n);});
Artisan::command('berita:pipeline-status',function(){$s=[];foreach(['pending','processing','review','scheduled','published','rejected','deferred','failed'] as $v)$s[$v]=Article::where('generation_status',$v)->count();$this->line(json_encode(['statuses'=>$s,'last_generation_errors'=>Article::whereNotNull('last_generation_error')->latest('updated_at')->limit(10)->pluck('last_generation_error')->values()],JSON_PRETTY_PRINT));});
Artisan::command('berita:gemini-health',function(){$m=config('berita.gemini_model','gemini-3.5-flash-lite');$key=config('services.gemini.key');$r=Http::timeout(10)->get('https://generativelanguage.googleapis.com/v1beta/models/'.$m, ['key'=>$key]);$this->line(json_encode(['model'=>$m,'http_status'=>$r->status(),'ok'=>$r->successful(),'reason'=>$r->successful()?null:'gemini_http_'.$r->status()]));});
Artisan::resolveCommands([AdminConsoleProcess::class]);
Schedule::command('berita:cycle')->everyThirtyMinutes()->withoutOverlapping(20);Schedule::command('berita:publish-scheduled')->everyTenMinutes()->withoutOverlapping(5);Schedule::command('berita:instagram-prepare')->everyFifteenMinutes()->withoutOverlapping(20);Schedule::command('berita:instagram-publish')->everyFifteenMinutes()->withoutOverlapping(20);Schedule::command('queue:work --stop-when-empty --max-time=50 --tries=2')->everyFiveMinutes()->withoutOverlapping(5);Schedule::command('admin-console:process')->everyMinute()->withoutOverlapping(5);
