<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('categories', function (Blueprint $t) { $t->id(); $t->string('name')->unique(); $t->timestamps(); });
        Schema::create('news_sources', function (Blueprint $t) { $t->id(); $t->string('source_id')->unique(); $t->string('publisher'); $t->string('name'); $t->text('feed_url'); $t->string('website_category')->nullable(); $t->unsignedInteger('weight')->default(1); $t->boolean('enabled')->default(true); $t->string('language', 12)->default('id'); $t->timestamp('last_success_at')->nullable(); $t->timestamp('last_failure_at')->nullable(); $t->text('last_error')->nullable(); $t->timestamps(); $t->index(['enabled','publisher']); });
        Schema::create('articles', function (Blueprint $t) { $t->id(); $t->string('slug')->unique(); $t->string('title'); $t->longText('content'); $t->text('excerpt')->nullable(); $t->foreignId('category_id')->nullable()->constrained()->nullOnDelete(); $t->string('source_id')->nullable(); $t->string('publisher')->nullable(); $t->string('source_name')->nullable(); $t->text('source_url')->nullable(); $t->text('canonical_url')->nullable(); $t->string('fingerprint',64)->unique(); $t->string('title_fingerprint',64)->nullable()->index(); $t->string('language',12)->default('id'); $t->text('image_url')->nullable(); $t->string('image_alt')->nullable(); $t->timestamp('source_published_at')->nullable(); $t->timestamp('site_published_at')->nullable(); $t->timestamp('updated_at_content')->nullable(); $t->string('generation_status')->default('published'); $t->json('metadata')->nullable(); $t->timestamps(); $t->index(['category_id','site_published_at']); });
        Schema::create('instagram_posts', function (Blueprint $t) { $t->id(); $t->foreignId('article_id')->constrained()->cascadeOnDelete(); $t->string('status')->default('draft'); $t->text('caption')->nullable(); $t->text('image_url')->nullable(); $t->string('container_id')->nullable()->unique(); $t->string('media_id')->nullable()->unique(); $t->unsignedInteger('attempt_count')->default(0); $t->text('last_error')->nullable(); $t->timestamp('prepared_at')->nullable(); $t->timestamp('published_at')->nullable(); $t->timestamp('last_attempt_at')->nullable(); $t->json('metadata')->nullable(); $t->timestamps(); $t->index(['status','prepared_at']); });
        Schema::create('instagram_preparations', function (Blueprint $t) { $t->id(); $t->string('run_uuid')->unique(); $t->string('status')->default('running'); $t->unsignedInteger('target')->default(0); $t->unsignedInteger('processed')->default(0); $t->unsignedInteger('ready')->default(0); $t->unsignedInteger('rejected')->default(0); $t->unsignedInteger('failed')->default(0); $t->unsignedInteger('remaining')->default(0); $t->timestamp('started_at')->nullable(); $t->timestamp('last_activity_at')->nullable(); $t->timestamp('completed_at')->nullable(); $t->text('last_error')->nullable(); $t->timestamps(); $t->index(['status','created_at']); });
        Schema::create('instagram_publish_queue', function (Blueprint $t) { $t->id(); $t->foreignId('instagram_post_id')->constrained('instagram_posts')->cascadeOnDelete(); $t->string('status')->default('READY'); $t->unsignedInteger('priority')->default(0); $t->timestamp('available_at')->nullable(); $t->unsignedInteger('attempt_count')->default(0); $t->timestamp('locked_at')->nullable(); $t->timestamp('published_at')->nullable(); $t->text('last_error')->nullable(); $t->timestamps(); $t->unique(['instagram_post_id']); $t->index(['status','available_at','priority']); });
        Schema::create('instagram_publish_attempts', function (Blueprint $t) { $t->id(); $t->foreignId('instagram_post_id')->constrained('instagram_posts')->cascadeOnDelete(); $t->foreignId('instagram_publish_queue_id')->nullable()->constrained('instagram_publish_queue')->nullOnDelete(); $t->string('status'); $t->string('container_id')->nullable(); $t->string('media_id')->nullable(); $t->unsignedInteger('attempt_no'); $t->text('error')->nullable(); $t->unsignedInteger('duration_ms')->nullable(); $t->timestamps(); $t->index(['instagram_post_id','attempt_no']); });
        Schema::create('automation_runs', function (Blueprint $t) { $t->id(); $t->uuid('run_uuid')->unique(); $t->string('type'); $t->string('trigger')->nullable(); $t->string('status')->default('running'); $t->unsignedInteger('target')->default(0); $t->unsignedInteger('processed')->default(0); $t->json('telemetry')->nullable(); $t->text('last_error')->nullable(); $t->timestamp('started_at')->nullable(); $t->timestamp('finished_at')->nullable(); $t->timestamps(); $t->index(['type','status','created_at']); });
        Schema::create('automation_locks', function (Blueprint $t) { $t->id(); $t->string('name')->unique(); $t->string('owner')->nullable(); $t->timestamp('expires_at')->nullable(); $t->timestamps(); });
        Schema::create('application_settings', function (Blueprint $t) { $t->id(); $t->string('key')->unique(); $t->text('value')->nullable(); $t->boolean('encrypted')->default(false); $t->timestamps(); });
        Schema::create('jobs', function (Blueprint $t) { $t->bigIncrements('id'); $t->string('queue')->index(); $t->longText('payload'); $t->unsignedTinyInteger('attempts'); $t->unsignedInteger('reserved_at')->nullable(); $t->unsignedInteger('available_at'); $t->unsignedInteger('created_at'); });
        Schema::create('job_batches', function (Blueprint $t) { $t->string('id')->primary(); $t->string('name'); $t->integer('total_jobs'); $t->integer('pending_jobs'); $t->integer('failed_jobs'); $t->longText('failed_job_ids'); $t->mediumText('options')->nullable(); $t->integer('cancelled_at')->nullable(); $t->integer('created_at'); $t->integer('finished_at')->nullable(); });
        Schema::create('failed_jobs', function (Blueprint $t) { $t->id(); $t->uuid('uuid')->unique(); $t->text('connection'); $t->text('queue'); $t->longText('payload'); $t->longText('exception'); $t->timestamp('failed_at')->useCurrent(); });
    }
    public function down(): void { foreach (['failed_jobs','job_batches','jobs','application_settings','automation_locks','automation_runs','instagram_publish_attempts','instagram_publish_queue','instagram_preparations','instagram_posts','articles','news_sources','categories'] as $table) Schema::dropIfExists($table); }
};
