<?php
namespace App\Http\Controllers;
use App\Models\{Article,AutomationRun,NewsSource};
use App\Services\Articles\ArticleQualityGate;
use Illuminate\Http\RedirectResponse;
class AdminController extends Controller {
 public function index(){ $query=Article::with('category'); if(request('q'))$query->where('title','like','%'.request('q').'%'); if(request('category'))$query->whereHas('category',fn($q)=>$q->where('name',request('category'))); if(request('source'))$query->where('source_name',request('source')); if(request('status'))$query->where('generation_status',request('status')); else $query->whereIn('generation_status',['draft','review','scheduled','published','rejected']); $articles=$query->latest('updated_at')->paginate(25)->withQueryString(); $gate=app(ArticleQualityGate::class); foreach($articles as $article){if($article->quality_score===null&&$article->generation_status!=='published'){ $check=$gate->check($article);$article->quality_score=$check['score'];$article->quality_reasons=$check['reasons']?implode(',',$check['reasons']):null; }} return view('admin.news',['articles'=>$articles,'sources'=>NewsSource::orderBy('name')->get(),'runs'=>AutomationRun::latest()->limit(10)->get()]); }
 public function approve(Article $article):RedirectResponse {if($article->generation_status==='review'){$article->reviewed_at=now();$article->generation_status='published';$article->site_published_at=now();$article->updated_at_content=now();$article->save();}return back();}
 public function reject(Article $article):RedirectResponse {$article->generation_status='rejected';$article->rejected_reason='editor_rejected';$article->reviewed_at=now();$article->save();return back();}
 public function publish(Article $article):RedirectResponse {if(in_array($article->generation_status,['draft','review'],true)){$article->reviewed_at=now();$article->generation_status='published';$article->site_published_at=now();$article->updated_at_content=now();$article->save();}return back();}
 public function schedule(Article $article):RedirectResponse {$when=request()->date('scheduled_at');if($when&&in_array($article->generation_status,['draft','review'],true)){$article->scheduled_at=$when;$article->generation_status='scheduled';$article->save();}return back();}
 public function edit(Article $article){return view('admin.article-edit',['article'=>$article,'categories'=>\App\Models\Category::orderBy('name')->get()]);}
 public function update(Article $article):RedirectResponse {$data=request()->validate(['title'=>['required','string','max:180'],'excerpt'=>['nullable','string','max:300'],'content'=>['required','string'],'category_id'=>['nullable','integer','exists:categories,id']]);$article->fill($data);$article->updated_at_content=now();$article->save();return redirect()->route('admin.news');}
}
