<?php
namespace App\Http\Controllers;
use App\Models\{Article,InstagramPost,InstagramPreparation,InstagramPublishQueue,AutomationRun,NewsSource};
use App\Services\{News\NewsIngestionService,Articles\ArticleGenerationService,Instagram\PreparationService,Instagram\PublisherService};
use Illuminate\Http\Request;
class AutomationController extends Controller {
 private function cron(Request $r):bool{$secret=config('berita.cron_secret');return !$secret||hash_equals($secret,(string)$r->header('X-Cron-Secret'));}
 public function health(){try{\DB::connection()->getPdo();$db=true;}catch(\Throwable){$db=false;}$last=AutomationRun::where('type','news_cycle')->latest('started_at')->first();$pub=Article::where('generation_status','published')->latest('site_published_at')->first();return response()->json(['database'=>$db,'automation_enabled'=>(bool)config('berita.automation_enabled'),'last_news_cycle_at'=>optional($last)->finished_at,'last_news_publish_at'=>optional($pub)->site_published_at,'pending_count'=>Article::where('generation_status','pending')->count(),'published_today'=>Article::where('generation_status','published')->whereDate('site_published_at',today())->count(),'deferred_count'=>Article::where('generation_status','deferred')->count(),'failed_count'=>Article::where('generation_status','failed')->count(),'last_cycle_status'=>optional($last)->status,'queue_ok'=>config('queue.default')!==null]);}
 public function newsPublish(Request $r,NewsIngestionService $ingest,ArticleGenerationService $publisher){if(!$this->cron($r))return response()->json(['message'=>'Unauthorized'],401);if(!config('berita.automation_enabled'))return response()->json(['status'=>'disabled']);$a=$ingest->run();return response()->json(['ingest'=>$a,'publish'=>$publisher->publishBatch()]);}
 public function socialPrepare(Request $r,PreparationService $s){if(!$this->cron($r))return response()->json(['message'=>'Unauthorized'],401);return response()->json($s->run((int)config('berita.instagram_prepare_max',3)));}
 public function socialPublish(Request $r,PublisherService $s){if(!$this->cron($r))return response()->json(['message'=>'Unauthorized'],401);return response()->json($s->run());}
 public function newsData(){return response()->json(['latest_cycle'=>AutomationRun::where('type','news_cycle')->latest()->first(),'published_today'=>Article::where('generation_status','published')->whereDate('site_published_at',today())->count(),'pending'=>Article::where('generation_status','pending')->count(),'deferred'=>Article::where('generation_status','deferred')->count(),'rejected'=>Article::where('generation_status','rejected')->count(),'latest_errors'=>Article::whereNotNull('last_generation_error')->latest()->limit(20)->get(['id','title','generation_status','last_generation_error','rejected_reason','deferred_reason']),'sources'=>NewsSource::orderBy('name')->get(),'articles'=>Article::where('generation_status','published')->with('category')->latest('site_published_at')->limit(50)->get()]);}
 public function instagramData(){return response()->json(['ready'=>InstagramPost::where('status','READY')->count(),'queue'=>InstagramPublishQueue::where('status','READY')->count(),'latest_preparation'=>InstagramPreparation::latest()->first(),'latest_published'=>InstagramPost::where('status','PUBLISHED')->latest('published_at')->first()]);}
}